# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52459676c9d888b607534d495d84b4c6d134ad1220d7395bf066ec8c3ad67a5dd0b3616cc92a5e06a5dd19fe0c92f7ae09b2d96069c19054a7de5bccf5466f1b

test:
  secret_key_base: 7ffc8af59aa9d8fcda47d5e5d4f65402e6e0ababb9e1733455f4f9e7c6d22925e0a918b5737e0b211ac71c0c0143ecf4b3759b29fecbcbbda98e1270c3bf9166

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
